version: '3'
services:
  remind-thing:
    image: registry.baidubce.com/liushao-repository/remind-thing:latest
    container_name: remind-thing
    restart: always
    ports:
      - 8080:8080
    environment:
      - COMPOSE_PROJECT_NAME=remind-thing
      - "SPRING_PROFILES_ACTIVE=prd"
      - TZ=Asia/Shanghai
    volumes:
      - ../../logs/:/logs/